# https://cloudinit.readthedocs.io/en/latest/reference/network-config.html
# https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v2.html
version: 2
ethernets:
  enp1s0 :
    # link-local: [ ipv4 ]
    dhcp4: true
