libvirt_uri: "qemu:///system"

pools:
- name: openstack
  path: "/vms/pools/openstack"

instances:
- name: controller
  count: 1
  memory: 2048
  vcpu: 2
  network: isolated
  pool: openstack
  image_source: "/vms/images/debian-12-generic-amd64-20241004-1890.qcow2"
  user_name: linux
  user_passwd: "$1$SaltSalt$m0TvXBlE13unrgk8.qpwd0"
  ssh_authorized_key: "~/.ssh/id_rsa.pub"
# - name: compute
#   count: 1
#   memory: 1024
#   vcpu: 2
#   network: isolated
#   pool: openstack
#   image_source: "/vms/images/debian-12-generic-amd64-20241004-1890.qcow2"
#   user_name: linux
#   user_passwd: "$1$SaltSalt$m0TvXBlE13unrgk8.qpwd0"
#   ssh_authorized_key: "~/.ssh/id_rsa.pub"
